config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'pages/gals'
  get 'pages/profil'
  get 'pages/login'
  get 'pages/design'
  get 'pages/classic'
  get 'pages/streetart'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mymuseum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", params[:controller], :media => "all" %>
    <%= javascript_include_tag "application", params[:controller] %>
    <%= javascript_include_tag :defaults %>.

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/classic.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag "classic" %>
  </head>
  <body>

    <div class="containerclassic">
      <br/>
      <br/>
    	<div class="gallery">

    		<div class="gallery-item">
    			<img class="gallery-image" src="https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?w=500&h=500&fit=crop" alt="person writing in a notebook beside by an iPad, laptop, printed photos, spectacles, and a cup of coffee on a saucer">
    		</div>

    		<div class="gallery-item">
    			<img class="gallery-image" src="https://images.unsplash.com/photo-1515260268569-9271009adfdb?w=500&h=500&fit=crop" alt="sunset behind San Francisco city skyline">
    		</div>

    		<div class="gallery-item">
    			<img class="gallery-image" src="https://images.unsplash.com/photo-1506045412240-22980140a405?w=500&h=500&fit=crop" alt="people holding umbrellas on a busy street at night lit by street lights and illuminated signs in Tokyo, Japan">
    		</div>

    		<div class="gallery-item">
    			<img class="gallery-image" src="https://images.unsplash.com/photo-1514041181368-bca62cceffcd?w=500&h=500&fit=crop" alt="car interior from central back seat position showing driver and blurred view through windscreen of a busy road at night">
    		</div>

    		<div class="gallery-item">
    			<img class="gallery-image" src="https://images.unsplash.com/photo-1445810694374-0a94739e4a03?w=500&h=500&fit=crop" alt="back view of woman wearing a backpack and beanie waiting to cross the road on a busy street at night in New York City, USA">
    		</div>

    		<div class="gallery-item">
    			<img class="gallery-image" src="https://images.unsplash.com/photo-1486334803289-1623f249dd1e?w=500&h=500&fit=crop" alt="man wearing a black jacket, white shirt, blue jeans, and brown boots, playing a white electric guitar while sitting on an amp">
    		</div>

    	</div>

    </div>

    <i class="fa fa-paint-brush return" onclick="goBack()"></i>

  </body>
</html>

app/views/pages/design.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
		<%= stylesheet_link_tag "design" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src='https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js'></script>
		<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
		<script src='https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js'></script>
		<script src='https://codepen.io/mican/pen/XgRmNr'></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css">
  </head>
  <body>

    <article class='gallery'>
  <a class='gallery-link' href='https://unsplash.it/1000/1000?image=1081'>
    <figure class='gallery-image'>
      <img height='1000' src='https://unsplash.it/1000/1000?image=1081' width='1000'>
      <figcaption>Photo caption</figcaption>
    </figure>
  </a>
  <a class='gallery-link' href='https://unsplash.it/1400/1200?image=1014'>
    <figure class='gallery-image'>
      <img height='1200' src='https://unsplash.it/1400/1200?image=1014' width='1400'>
      <figcaption>Photo caption</figcaption>
    </figure>
  </a>
  <a class='gallery-link' href='https://unsplash.it/1000/1200?image=267'>
    <figure class='gallery-image'>
      <img height='1200' src='https://unsplash.it/1000/1200?image=267' width='1000'>
      <figcaption>Photo caption</figcaption>
    </figure>
  </a>
  <a class='gallery-link' href='https://unsplash.it/1600/1400?image=266'>
    <figure class='gallery-image'>
      <img height='1400' src='https://unsplash.it/1600/1400?image=266' width='1600'>
      <figcaption>Photo caption</figcaption>
    </figure>
  </a>
  <a class='gallery-link' href='https://unsplash.it/1200/1400?image=634'>
    <figure class='gallery-image'>
      <img height='1400' src='https://unsplash.it/1200/1400?image=634' width='1200'>
      <figcaption>Photo caption</figcaption>
    </figure>
  </a>
  <a class='gallery-link' href='https://unsplash.it/1600/1400?image=923'>
    <figure class='gallery-image'>
      <img height='1400' src='https://unsplash.it/1600/1400?image=923' width='1600'>
      <figcaption>Photo caption</figcaption>
    </figure>
  </a>
  <a class='gallery-link' href='https://unsplash.it/1200/1600?image=682'>
    <figure class='gallery-image'>
      <img height='1600' src='https://unsplash.it/1200/1600?image=682' width='1200'>
      <figcaption>Photo caption</figcaption>
    </figure>
  </a>
  <a class='gallery-link' href='https://unsplash.it/1000/1400?image=173'>
    <figure class='gallery-image'>
      <img height='1400' src='https://unsplash.it/1000/1400?image=173' width='1000'>
      <figcaption>Photo caption</figcaption>
    </figure>
  </a>
  <a class='gallery-link' href='https://unsplash.it/1000/1400?image=943'>
    <figure class='gallery-image'>
      <img height='1400' src='https://unsplash.it/1000/1400?image=943' width='1000'>
      <figcaption>Photo caption</figcaption>
    </figure>
  </a>
</article>
<footer id='footer' role='contentinfo'>
</footer>


<i class="fa fa-paint-brush return" onclick="goBack()"></i>


  </body>
</html>

app/views/pages/gals.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js'></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag "gals" %>

  </head>
  <body>

    <nav>
    	<a href="<%=pages_home_path%>"><h1>My Museum</h1></a>

      <div class="navright">
			  <a href="<%=pages_login_path%>" class="btnlogin">Log In / Sign Up</a>
			</div>

		</nav>

    <div class="subtitle">
			<p>Votre Gallerie</p>
		</div>


    <ul class="honeycomb" lang="es">
  <li class="honeycomb-cell">
    <img class="honeycomb-cell__image" src="https://source.unsplash.com/random/1">
    <div class="honeycomb-cell__title"><a href="<%=pages_design_path%>">Design</a></div>
  </li>
  <li class="honeycomb-cell">
    <img class="honeycomb-cell__image" src="https://source.unsplash.com/random/2">
    <div class="honeycomb-cell__title">Classic</div>
  </li>
  <li class="honeycomb-cell">
    <img class="honeycomb-cell__image" src="https://source.unsplash.com/random/3">
    <div class="honeycomb-cell__title">Street Art</div>
  </li>
  <li class="honeycomb-cell">
    <img class="honeycomb-cell__image" src="https://source.unsplash.com/random/4">
    <div class="honeycomb-cell__title">Coeval</div>
  </li>
  <li class="honeycomb-cell">
    <img class="honeycomb-cell__image" src="https://source.unsplash.com/random/5">
    <div class="honeycomb-cell__title">Surrealist</div>
  </li>
  <li class="honeycomb-cell">
    <img class="honeycomb-cell__image" src="https://source.unsplash.com/random/6">
    <div class="honeycomb-cell__title">Polaroid</div>
  </li>
  <li class="honeycomb-cell">
    <img class="honeycomb-cell__image" src="https://source.unsplash.com/random/7">
    <div class="honeycomb-cell__title">Tablero magnético</div>
  </li>
  <li class="honeycomb-cell honeycomb__placeholder"></li>
</ul>


    <i class="fa fa-paint-brush return" onclick="goBack()"></i>


  </body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title></title>
		<link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js'></script>
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag "mymuseum" %>
  </head>
	<body>

		<nav>
    	<a href="<%=pages_home_path%>"><h1>My Museum</h1></a>

			<!--<div class="frames">
			  <img src="https://img.icons8.com/ios-filled/50/000000/frame.png">
				<img src="https://img.icons8.com/ios/50/000000/frame.png">
				<img src="https://img.icons8.com/doodle/48/000000/hanging-frame.png">
				<img src="https://img.icons8.com/ios/50/000000/frame.png">
				<img src="https://img.icons8.com/ios-filled/50/000000/frame.png">
			</div>-->

			<div class="navright">
			  <a href="login.html" class="btnlogin">Log In / Sign Up</a>
			</div>

		</nav>

		<div class="mainimg">
			<div class="textmainimg">
				<h2>Créer votre gallerie</h2>
				<p>Enfin de vrais galleries pour vos oeuvres</p>
			</div>
		</div>


		<div class="containersteps">
		  <div class="at-section">
		    <div class="at-section__title">Your masterpieces, our gallery</div>
		  </div>
		  <div class="at-grid" data-column="3">
		    <div class="at-column">
		      <div class="at-user">
		        <div class="at-user__avatar"><i class="fa fa-user" style="color:#fbcdbe"></i></div>
		        <div class="at-user__name">1. Votre profil</div>
		        <div class="at-user__title">Enter your infos on your profil and let's get ready to rumble</div>
		      </div>
		    </div>
		    <div class="at-column">
		      <div class="at-user">
		        <div class="at-user__avatar"><i class="fa fa-download" style="color:#cdbcb5"></i></div>
		        <div class="at-user__name">2. Vos oeuvres</div>
		        <div class="at-user__title">Download your artworks ( paintings, photos, videos, ... )</div>
		      </div>
		    </div>
		    <div class="at-column">
		      <div class="at-user">
		        <div class="at-user__avatar"><i class="fa fa-font" style="color:#f0c3a3"></i></div>
		        <div class="at-user__name">3. Description</div>
		        <div class="at-user__title">Details each one of your artworks with a good description</div>
		      </div>
		    </div>
		    <div class="at-column">
		      <div class="at-user">
		        <div class="at-user__avatar"><i class="fa fa-image" style="color:#80b7d5"></i></div>
		        <div class="at-user__name">4. Votre gallerie</div>
		        <div class="at-user__title">Try and choose one of our gallery, your artworks are already here waiting for you </div>
		      </div>
		    </div>
		    <div class="at-column">
		      <div class="at-user">
		        <div class="at-user__avatar"><i class="fa fa-gear" style="color:#c9e4b4"></i></div>
		        <div class="at-user__name">5. Personnaliser</div>
		        <div class="at-user__title">Custom your gallerie as you wish. Congrats, it's your's now</div>
		      </div>
		    </div>
		    <div class="at-column">
		      <div class="at-user">
		        <div class="at-user__avatar"><i class="fa fa-check-circle" style="color:#cfb4e4"></i></div>
		        <div class="at-user__name">6. C'est prêt !</div>
		        <div class="at-user__title">Créer votre site MyMuseum ou insérer la gallerie dans le votre </div>
		      </div>
		    </div>

		    </div>

				<div class="begin">
				  <a href="<%=pages_profil_path%>" class="toprofil">Open your store</a>
			  </div>

		  </div>
		</div>








		<div class="container">
			<h2 class="subtitle">Nos galleries</h2>
			<article class="post wiggle-me">
				<img width="660" height="478" src="http://www.sightunseen.com/content/uploads/2015/03/studio_1.jpg" class="post-image" alt="post-image">
				<section class="post-content">
					<time class="post-date">1400 - 1487</time>
					<h1 class="post-title">Design</h1>
					<p class="post-abstract">Un modèle pour les artistes de la nouvelle vague, la grande, la belle vague</p>
					<div class="post-link-c">
						<a href="<%=pages_design_path%>" class="post-link">Choose</a>
					</div>
				</section>

			</article>
			<article class="post wiggle-me">
				<img width="660" height="523" src="http://www.sightunseen.com/content/uploads/2015/11/Brazil_Modern2.jpg" class="post-image" alt="">
				<section class="post-content">
					<time class="post-date">Friday 14 November, 13:00</time>
					<h1 class="post-title">Classic</h1>
					<p class="post-abstract">Une gallerie ma fois tout ce qu'il y a de plus classique mais toujours très efficace</p>
					<div class="post-link-c">
						<a href="<%=pages_classic_path%>" class="post-link">Choose</a>
					</div>
				</section>

			</article>
			<article class="post wiggle-me">
				<img width="660" height="478" src="http://www.sightunseen.com/content/uploads/2015/03/studio_1.jpg" class="post-image" alt="">
				<section class="post-content">
					<time class="post-date">Saturday 45 November</time>
					<h1 class="post-title">Street Art</h1>
					<p class="post-abstract">Pour les plus Underground d'entre nous faite est cette gallerie - Yoda</p>
					<div class="post-link-c">
						<a href="<%=pages_streetart_path%>" class="post-link">Choose</a>
					</div>
				</section>

			</article>
			<article class="post wiggle-me">
				<img width="660" height="478" src="http://www.sightunseen.com/content/uploads/2015/03/studio_1.jpg" class="post-image" alt="">
				<section class="post-content">
					<time class="post-date">Saturday 28 November, 14:00</time>
					<h1 class="post-title">Coeval</h1>
					<p class="post-abstract">Contemporain c'est pas tout ce qu'y s'passe à la campagne non ?</p>
					<div class="post-link-c">
						<a href="coeval.html" class="post-link">Choose</a>
					</div>
				</section>
			</article>

			<article class="post wiggle-me">
				<img width="660" height="523" src="http://www.sightunseen.com/content/uploads/2015/11/Brazil_Modern2.jpg" class="post-image" alt="">
				<section class="post-content">
					<time class="post-date">Friday 14 November, 13:00</time>
					<h1 class="post-title">Surrealist</h1>
					<p class="post-abstract">ɿυɈυʇ ǝl ƨnɒb ɒįǝb Ɉnǝviv iυp ƨǝɈƨiɈɿɒ ƨǝl ɿυoꟼ</p>
					<div class="post-link-c"><a href="surrealist.html" class="post-link">Choose</a></div>
				</section>
			</article>

			<article class="post wiggle-me">
				<img width="660" height="478" src="http://www.sightunseen.com/content/uploads/2015/03/studio_1.jpg" class="post-image" alt="">
				<section class="post-content">
					<time class="post-date">Saturday 45 November</time>
					<h1 class="post-title">Polaroid</h1>
					<p class="post-abstract">Une gallerie pour surfer sur le nouveau succès d'anciennes photos </p>
					<div class="post-link-c"><a href="polaroid.html" class="post-link">Choose</a></div>
				</section>
			</article>

		</div>

		<div class="divgals"><a href="<%=pages_gals_path%>" class="moregal">See more</a></div>

		<h2 class="subtitle">For artists, by artists</h2>
		<p class="samplep">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
		<div class="sample"></div>
		


<footer>

	<a href="mymuseum.html" class="block">@MyMuseum</a>
	<br/>
	<br/>

	<div class="socials">

		<a href=""><i class="fa fa-facebook"></i></a>
		<a href=""><i class="fa fa-instagram"></i></a>
		<a href=""><i class="fa fa-linkedin"></i></a>

	</div>

	<br/>

	<div class="footlink">
		<a href="">Help</a>
		<a href="">Blog</a>
		<a href="">Legal</a>
	</div>

</footer>

<i class="fa fa-paint-brush return" onclick="goBack()"></i>








</body>
</html>

app/views/pages/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js'></script>
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		<%= stylesheet_link_tag "login" %>
  </head>
  <body>

    <div class="brand">
      <a href="<%=pages_home_path%>">My Museum</a>
    </div>

    <h2 class="subtitle">My Museum wants you to join !</h2>
    <div class="form">

      <ul class="tab-group">
        <li class="tab active"><a href="#signup">Sign Up</a></li>
        <li class="tab"><a href="#login">Log In</a></li>
      </ul>

      <div class="tab-content">
        <div id="signup">
          <h1>Sign Up for Free</h1>

          <form action="/" method="post">

          <div class="top-row">
            <div class="field-wrap">
              <label>
                First Name<span class="req">*</span>
              </label>
              <input type="text" required autocomplete="off" />
            </div>

            <div class="field-wrap">
              <label>
                Last Name<span class="req">*</span>
              </label>
              <input type="text"required autocomplete="off"/>
            </div>
          </div>

          <div class="field-wrap">
            <label>
              Email<span class="req">*</span>
            </label>
            <input type="email"required autocomplete="off"/>
          </div>

          <div class="field-wrap">
            <label>
              Password<span class="req">*</span>
            </label>
            <input type="password"required autocomplete="off"/>
          </div>

          <button type="submit" class="button button-block"/>Get Started</button>

          </form>

        </div>

        <div id="login">
          <h1>Welcome Back!</h1>

          <form action="/" method="post">

            <div class="field-wrap">
            <label>
              Email<span class="req">*</span>
            </label>
            <input type="email"required autocomplete="off"/>
          </div>

          <div class="field-wrap">
            <label>
              Password<span class="req">*</span>
            </label>
            <input type="password"required autocomplete="off"/>
          </div>

          <p class="forgot"><a href="#">Forgot Password?</a></p>

          <button class="button button-block"/>Log In</button>

          </form>

        </div>

      </div><!-- tab-content -->

</div> <!-- /form -->


  <i class="fa fa-paint-brush return" onclick="goBack()"></i>


  </body>
</html>

app/views/pages/profil.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js'></script>
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag "profil" %>
  </head>
  <body>

    <section class="navigation">
      <div class="nav-container">
        <div class="brand">
          <a href="<%=pages_home_path%>">My Museum</a>
        </div>
        <nav>
          <div class="nav-mobile"><a id="nav-toggle" href="#!"><span></span></a></div>
          <ul class="nav-list">
            <li>
              <a href="profil.html">Profil</a>
            </li>
            <li>
              <a href="oeuvres.html">Oeuvres</a>
            </li>
            <li>
              <a href="#!">Services</a>
              <ul class="nav-dropdown">
                <li>
                  <a href="#!">Web Design</a>
                </li>
                <li>
                  <a href="#!">Web Development</a>
                </li>
                <li>
                  <a href="#!">Graphic Design</a>
                </li>
              </ul>
            </li>
            <li>
              <a href="custom.html">Custom</a>
            </li>
            <li>
              <a href="#!">Portfolio</a>
              <ul class="nav-dropdown">
                <li>
                  <a href="#!">Web Design</a>
                </li>
                <li>
                  <a href="#!">Web Development</a>
                </li>
                <li>
                  <a href="#!">Graphic Design</a>
                </li>
              </ul>
            </li>
            <li>
              <a href="#!">Contact</a>
            </li>
          </ul>
        </nav>
      </div>
    </section>




    <h4>Multiple Upload with preview and order</h4>
    <div class="block">
      <label class="button" for="images">Upload Images</label>
      <input type="file" id="images" multiple="multiple"/>
      <div id="multiple-file-preview">
        <ul id="sortable">
          <div class="clear-both"></div>
        </ul>
      </div>
    </div>

<i class="fa fa-paint-brush return" onclick="goBack()"></i>




  </body>
</html>

app/views/pages/streetart.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag "streetart" %>
  </head>
  <body>

    <figure id="showcase">
      <section></section>
      <section></section>
      <section></section>
      <section></section>
    </figure>


    <i class="fa fa-paint-brush return" onclick="goBack()"></i>


  </body>
</html>